title: allyoushawn's homepage
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  GitHub Profile: https://github.com/allyoushawn

plugins:
  - jemoji